"""Initial migration

Revision ID: f005209f73c8
Revises: 
Create Date: 2024-01-06 00:11:03.727949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f005209f73c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('BookId', sa.Integer(), nullable=False),
    sa.Column('PageNum', sa.Integer(), nullable=True),
    sa.Column('BookName', sa.String(length=100), nullable=True),
    sa.Column('Author', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('BookId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('books')
    # ### end Alembic commands ###
